### ISSUE TITLE
Please build and push new version of guard-less to rubygems.org

### ISSUE THREAD

**Issue by saghaulor** [guard/guard-less#16]
The current version of guard-less on rubygems requires less v2.1. The current github version can use ~> 2.3. In less 2.2 there were significant performance enhancements introduced, as well as removing the requirement for therubyracer. Simply pushing a new version to rubygems would assist in relieving a lot of dependency headache as well as getting much needed performance improvements. Thank you in advance!

**Comment by e2** [comment]
Sorry for the tremendous wait, folks!

v2.0.0 is released.

Let me know if there are any issues.
