### ISSUE TITLE
Compile Bootstrap with guard-less

### ISSUE THREAD

**Issue by kossa** [guard/guard-less#21]
I'm looking for Guardfile to compile less of bootstrap, but I did not found anything

**Comment by e2** [comment]
If I understand correctly, you want to know what options to use so guard-less can find and compile bootstrap as less files.

It should work if patterns is the default. What is your project structure? Where are the bootstrap less files located?

There is also a `:import_paths` option you may need.

**Comment by kossa** [comment]
Sorry, I think I wasn't clear 
I have a root project, inside 2 folder, one all less(Bootstrap + myFile.less) and css folder, so in the css I want only bootstrap.css and main.css
I dont know what shall I put in the patterns :)

**Comment by kossa** [comment]
@e2 :
`less_options = {
  all_on_start: true,
  all_after_change: true,
  output: 'css',
  import_paths: ['less'],
  patterns: [/^bootstrap.less$/]
}

guard :less, less_options do
  less_options[:patterns].each { |pattern| watch(pattern) }
end
`

**Comment by e2** [comment]
What is the structure for your project? Where is the bootstrap.less file located? You should be able to also add myFile.less to the patterns array and it should work.
Ideally, you may have e.g.:
```
lib/bootstrap/less/bootstrap.less  # copied from twitter boostrap less dir
source/myFile.less
```
And then the patterns should be e.g.: 
```ruby
patterns: [/^lib\/bootstrap\/less\/bootstrap.less$/, /^source\/myFile.less$/`]
```

**Comment by e2** [comment]
You don't need the import path if you e.g. copied the whole less directory from bootstrap - the bootstrap.less file imports all the other less files, so it's the only file you need in the pattern.

**Comment by kossa** [comment]
Alright It works, but the only problem now, I see all files compiled in css folder: http://i.imgur.com/MOWdTnR.png

**Comment by kossa** [comment]
For the moment I just want to try bootstrap with single HTML file, and understanding the Guardfile :)

**Comment by kossa** [comment]
Thank you @e2 for the help (y)
Now when I make some changes on less/variables.css, but nothing changes(I'm using guard-livereload too), when I reload guard, it works. 
So how can I watch all files in /less and get in the output only bootstrap.css ?

**Comment by kossa** [comment]
I found the solution :)
I forgot to watch in `guard :less`
```
# Watch all files
guard 'livereload' do
  watch(%r{.+\..*$})
end

less_options = {
  all_on_start: true,
  all_after_change: true,
  output: 'css',
  patterns: [/^less\/bootstrap.less$/]
}

guard :less, less_options do
  less_options[:patterns].each { |pattern| watch(pattern) }
  watch(%r{.+\..*$}) #once we convert we do a new watch
end

```

**Comment by e2** [comment]
Yes, ideally you wouldn't want to modify boostrap files - it's better to have your own overriding css e.g. 'bootstrap_overrides.less' in your project.

I think rebuilding the bootstrap.css is useful only e.g. if you're debugging and fixing bootstrap itself (for bugfixes, pull requests, etc.).

If you just want to cut parts out of bootstrap, you may prefer a custom build first: http://getbootstrap.com/customize/

For the watchers, you can do: 
```ruby
guard :less, less_options do
  (less_options[:patterns] + [%r{.+\.less$}]).each { |pattern| watch(pattern) }
end
```

That's because the order of watches is only important for matching - guard-less is run if anything matches any of the watches. (Guard first tries to find matches, and executes afterwards - outside the block).

**Comment by kossa** [comment]
Many thanks @e2, as I said, I just tried Bootstrap with Guard, and I never changed Bootstrap files, may be variables.less, but creating a new file will be the good idea ;)

**Comment by e2** [comment]
It's based on the source file always: https://github.com/guard/guard-less/blob/master/lib/guard/less.rb#L49

So if you have e.g. myfile.less and you want it to become app.css, all you need to do is:
1. create a new file `app.less` with `@import 'myfile.less'`
2. prevent `myfile.less` from matching the patterns

That way, guard-less will match app.less, and compile it to app.css. So for every `*.css` file you want, you need a matching `*.less` file - and you need to ignore every other file (to avoid duplicate content).

**Comment by kossa** [comment]
Ahh right, good idea.Thank you @e2
